#!/usr/bin/env bash
set -eu

cargo test

echo "==> Debug mode: fragment file changes cause reloaded PSOs"
cargo run --example fragment-change

echo "==> Release mode: fragment file included as bytes so file changes have no effect"
cargo run --example fragment-change --release
